### ISSUE TITLE
4주차 페어

### ISSUE THREAD

**Issue by weweweme** [haedal-study/1-percent-network#35]
4주차 페어가 아직 설정되지 않은 것 같아, 앞주차 페어들이 짜여진 규칙을 보고 짜봤습니다.

@ChoiSeonMun <-> @daheeParkk
@songsunkook <-> @weweweme
@daepan <-> @dooohun
@Invidam <-> @johnny19991006
@ChoiSeonMun <-> @JunghyeonShin

**Comment by Invidam** [comment]
좋습니다!! 😋

**Comment by ChoiSeonMun** [comment]
@ChoiSeonMun <-> @daheeParkk 
@songsunkook <-> @weweweme 
@daepan <-> @johnny19991006 
@Invidam <-> @JunghyeonShin
